from __future__ import annotations

from typing import Any, Dict, List

from sce.core.actions import Action
from sce.core.planning import Plan
from sce.core.types import State


class LLMPlanner:
    """Generate small action plans from an LLM JSON response.

    The planner expects a client with a `complete_json(prompt) -> dict` method.
    It returns a `Plan` compatible with the existing planning layer.
    """

    def __init__(self, llm_client: Any) -> None:
        self.llm = llm_client

    def plan(self, state: State, goal: str) -> Plan:
        prompt = self._build_prompt(state, goal)
        payload = self.llm.complete_json(prompt)
        steps = payload.get("steps", [])
        if not isinstance(steps, list):
            raise ValueError("LLM planner payload must include a 'steps' list")

        actions: List[Action] = []
        for index, step in enumerate(steps):
            if not isinstance(step, dict):
                raise ValueError(f"Plan step at index {index} must be an object")
            name = step.get("name") or "unknown"
            description = step.get("description") or ""
            tool = step.get("tool")
            arguments = step.get("arguments") or {}
            if not isinstance(arguments, dict):
                raise ValueError(f"Plan step arguments at index {index} must be an object")

            actions.append(
                Action(
                    name=name,
                    description=description,
                    action_type="tool" if tool else "workflow",
                    payload={
                        "tool": tool,
                        "arguments": arguments,
                    },
                )
            )

        return Plan(
            name="llm_generated_plan",
            actions=actions,
            reason="Generated by LLM planner",
            meta={"goal": goal},
        )

    def _build_prompt(self, state: State, goal: str) -> str:
        return f"""
You are a planning system for SCE Core.

Goal:
{goal}

Current state:
{state.data}

Generate a short plan as JSON.
Return an object with a top-level 'steps' list.
Each step must contain:
- name
- description
- tool (optional)
- arguments (optional)

Example:
{{
  "steps": [
    {{
      "name": "fetch_supplier_risk",
      "description": "Fetch supplier risk data",
      "tool": "supplier_risk_api",
      "arguments": {{"supplier_id": "supplier A"}}
    }},
    {{
      "name": "request_review",
      "description": "Escalate for review",
      "arguments": {{}}
    }}
  ]
}}
""".strip()
